In [51]:
%matplotlib inline 
import os
from glob import glob 
import pandas as pd
import matplotlib.pyplot as plt 

snapshots_path  = '../snapshots_fulltraining/'

## Listing all h5 files not converted as inference
models = [f for f in glob(f'{snapshots_path}*.h5') if 'infer' not in f]

## Listing the first result file in the directory 
results = [glob(f'{snapshots_path}*.csv')][0][0]

models, results

(['../snapshots_fulltraining/resnet50_csv_14.h5',
  '../snapshots_fulltraining/resnet50_csv_23.h5',
  '../snapshots_fulltraining/resnet50_csv_17.h5',
  '../snapshots_fulltraining/resnet50_csv_20.h5',
  '../snapshots_fulltraining/resnet50_csv_10.h5',
  '../snapshots_fulltraining/resnet50_csv_01.h5',
  '../snapshots_fulltraining/resnet50_csv_03.h5',
  '../snapshots_fulltraining/resnet50_csv_09.h5',
  '../snapshots_fulltraining/resnet50_csv_19.h5',
  '../snapshots_fulltraining/resnet50_csv_13.h5',
  '../snapshots_fulltraining/resnet50_csv_25.h5',
  '../snapshots_fulltraining/resnet50_csv_22.h5',
  '../snapshots_fulltraining/resnet50_csv_07.h5',
  '../snapshots_fulltraining/resnet50_csv_04.h5',
  '../snapshots_fulltraining/resnet50_csv_05.h5',
  '../snapshots_fulltraining/resnet50_csv_11.h5',
  '../snapshots_fulltraining/resnet50_csv_16.h5',
  '../snapshots_fulltraining/resnet50_csv_15.h5',
  '../snapshots_fulltraining/resnet50_csv_21.h5',
  '../snapshots_fulltraining/resnet50_csv_24.h5',
  '../snapshots_fulltraining/resnet50_csv_06.h5',
  '../snapshots_fulltraining/resnet50_csv_12.h5',
  '../snapshots_fulltraining/resnet50_csv_18.h5',
  '../snapshots_fulltraining/resnet50_csv_08.h5',
  '../snapshots_fulltraining/resnet50_csv_02.h5'],
 '../snapshots_fulltraining/2018-11-24-0631_resnet50.csv')

## Selecting the best 5 models given rsna_score

In [24]:
df_results = pd.read_csv(results)
best_rsna_scores = df_results.sort_values('y_rsna_score', ascending=False).head(5)
best_rsna_scores_models = best_rsna_scores['Unnamed: 0'].values
best_rsna_scores

,Unnamed: 0,loss,regression_loss,classification_loss,y_thresh,y_rsna_score,y_se,y_sp,max_youden,lr
15,15,2.015240,1.443428,0.571812,0.05,0.142869,0.583039,0.921158,0.504197,0.01
21,21,1.964127,1.399836,0.564291,0.05,0.140080,0.664311,0.901198,0.565509,0.01
20,20,1.976573,1.412956,0.563617,0.05,0.139994,0.547703,0.933134,0.480837,0.01
18,18,2.003239,1.421098,0.582141,0.06,0.137590,0.671378,0.890220,0.561598,0.01
24,24,1.983557,1.413766,0.569791,0.05,0.130206,0.692580,0.898204,0.590783,0.01

## Selecting the 5 best Loss models

In [38]:
best_loss = df_results.sort_values('loss', ascending=True).head(5)
best_loss_models = best_loss['Unnamed: 0'].values
best_loss

,Unnamed: 0,loss,regression_loss,classification_loss,y_thresh,y_rsna_score,y_se,y_sp,max_youden,lr
23,23,1.954690,1.396192,0.558498,0.05,0.125979,0.692580,0.887226,0.579805,0.01
21,21,1.964127,1.399836,0.564291,0.05,0.140080,0.664311,0.901198,0.565509,0.01
20,20,1.976573,1.412956,0.563617,0.05,0.139994,0.547703,0.933134,0.480837,0.01
19,19,1.978791,1.419019,0.559771,0.05,0.122533,0.717314,0.865269,0.582584,0.01
22,22,1.979219,1.416211,0.563008,0.05,0.119773,0.752650,0.843313,0.595964,0.01

In [39]:
best_models_intersection = [m for m in best_rsna_scores_models if m in best_loss_models]
best_models_intersection

[21, 20]

## Selecting the best models by classification loss

In [44]:
best_classification_loss = df_results.sort_values('classification_loss', ascending=True).head(5)
best_classification_loss_models = best_loss['Unnamed: 0'].values
best_classification_loss

,Unnamed: 0,loss,regression_loss,classification_loss,y_thresh,y_rsna_score,y_se,y_sp,max_youden,lr
23,23,1.954690,1.396192,0.558498,0.05,0.125979,0.692580,0.887226,0.579805,0.01
19,19,1.978791,1.419019,0.559771,0.05,0.122533,0.717314,0.865269,0.582584,0.01
22,22,1.979219,1.416211,0.563008,0.05,0.119773,0.752650,0.843313,0.595964,0.01
20,20,1.976573,1.412956,0.563617,0.05,0.139994,0.547703,0.933134,0.480837,0.01
21,21,1.964127,1.399836,0.564291,0.05,0.140080,0.664311,0.901198,0.565509,0.01

In [45]:
best_models_intersection = [m for m in best_models_intersection if m in best_classification_loss_models]
best_models_intersection

[21, 20]

In [ ]:
Converting the m

In [70]:
selected_models = [m.replace('../', './') for m in models if int(os.path.basename(m)[:-3].split('_')[-1]) in best_models_intersection]
for m in selected_models:    
    print (f"\n Converting Model {m} \n\n")
    !cd .. && sh ./convert_model.sh {m} {m.replace('csv', 'infer')}

 Converting Model ./snapshots_fulltraining/resnet50_csv_20.h5


Using TensorFlow backend.
2018-11-24 21:46:45.674205: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-11-24 21:46:45.677847: E tensorflow/stream_executor/cuda/cuda_driver.cc:397] failed call to cuInit: CUDA_ERROR_NO_DEVICE
2018-11-24 21:46:45.677885: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for host: 89d0f7b727a6
2018-11-24 21:46:45.677896: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: 89d0f7b727a6
2018-11-24 21:46:45.677947: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: 410.72.0
2018-11-24 21:46:45.677997: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 410.72.0
2018-11-24 21:46:45.678008: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:300] kernel version seems to match DSO: 410.72.0

 Converting Model ./snapshots_fulltraining/resnet50_csv_21.h5


Using TensorFlow backend.
2018-11-24 21:47:04.963214: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-11-24 21:47:04.966462: E tensorflow/stream_executor/cuda/cuda_driver.cc:397] failed call to cuInit: CUDA_ERROR_NO_DEVICE
2018-11-24 21:47:04.966505: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for host: 89d0f7b727a6
2018-11-24 21:47:04.966515: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: 89d0f7b727a6
2018-11-24 21:47:04.966567: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: 410.72.0
2018-11-24 21:47:04.966602: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 410.72.0
2018-11-24 21:47:04.966612: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:300] kernel version seems to match DSO: 410.72.0